CREATE DATABASE GymJunky
GO

USE GymJunky
GO

CREATE TABLE Kategorije
(
KategorijaId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Naziv NVARCHAR(MAX),
);
GO
CREATE TABLE Programi
(
ProgramId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Naziv NVARCHAR(MAX),
Opis NVARCHAR(MAX),
BrojTreninga NVARCHAR(MAX),
VrijemeTrajanja NVARCHAR(MAX),
KategorijaId INT FOREIGN KEY REFERENCES Kategorije(KategorijaId)
);
GO

CREATE TABLE Igraci	
(
IgracId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
KorisnickoIme NVARCHAR(MAX),
Lozinka NVARCHAR(MAX),
Email NVARCHAR(MAX),
Visina INT,
Tezina INT
);
CREATE TABLE IgraciProgrami(
IgraciProgrami INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IgracId INT FOREIGN KEY REFERENCES Igraci(IgracId),
ProgramId INT FOREIGN KEY REFERENCES Programi(ProgramId)
);
GO
CREATE LOGIN ib140151   
    WITH PASSWORD = '140151';  
GO  
 
CREATE USER ib140151 FOR LOGIN ib140151;  
GO  